# Configuración de SonarQube para el proyecto Yoliztli
sonar.projectKey=Yoliztli
sonar.projectName=Yoliztli
sonar.projectVersion=1.0

# Directorios de código fuente a analizar
sonar.sources=app,resources/js,routes
# Directorio de pruebas
sonar.tests=tests

# Codificación de archivos
sonar.sourceEncoding=UTF-8

# Exclusiones de carpetas que no requieren análisis estático
sonar.exclusions=vendor/**,node_modules/**,public/**,bootstrap/cache/**,storage/**,database/**,Documentation/**

# Dirección de SonarQube
sonar.host.url=http://localhost:9000

# Token de acceso global reutilizable
sonar.token=squ_fb5a2f5c48dd4637a84fc3cd0f58ad6746f1d76b

